### ISSUE TITLE
Add `cudatoolkit-dev` as requirement in `py-xgboost-gpu` 

### ISSUE THREAD

**Issue by ksangeek** [AnacondaRecipes/xgboost-feedstock#1]
Include `cudatoolkit-dev` as a requirement in the `host` section of the `meta.yaml` for the branch to build the GPU version of `py-xgboost`. This change is required to use `nvcc` for building CUDA code.
This change is required in the `host` section for the outputs `libxgboost` and `py-xgboost`.

**Comment by jjhelmus** [comment]
`cudatoolkit-dev` is not a package provided by Anaconda.  Installation of `nvcc` is left to the user.
